void png() {
  brick = loadImage("mario_terrain/brick.png");
  brick.resize(gridSize, gridSize);
  ladder = loadImage("mario_terrain/ladder.png");
  ladder.resize(gridSize, gridSize);
  ice = loadImage("mario_terrain/blueBlock.png");
  ice.resize(gridSize, gridSize);
  trampDown = loadImage("mario_terrain/trampolineDown.png");
  trampDown.resize(gridSize, gridSize);
  trampMid = loadImage("mario_terrain/trampolineMid.png");
  trampMid.resize(gridSize, gridSize);
  trampUp = loadImage("mario_terrain/trampolineUp.png");
  trampUp.resize(gridSize, gridSize);
  treeEast = loadImage("mario_terrain/treetop_e.png");
  treeEast.resize(gridSize, gridSize);
  treeNormal = loadImage("mario_terrain/treetop_center.png");
  treeNormal.resize(gridSize, gridSize);
  treeWest = loadImage("mario_terrain/treetop_w.png");
  treeWest.resize(gridSize,gridSize);
  treeIntersect = loadImage("mario_terrain/tree_intersect.png");
  treeIntersect.resize(gridSize,gridSize);
  tree_Trunk = loadImage("mario_terrain/tree_trunk.png");
  tree_Trunk.resize(gridSize,gridSize);
  spike = loadImage("mario_terrain/spike.png");
  spike.resize(gridSize,gridSize);
  bridgeWest = loadImage("mario_terrain/bridge_w.png");
  bridgeWest.resize(gridSize,gridSize);
  bridgeMiddle = loadImage("mario_terrain/bridge_center.png");
  bridgeMiddle.resize(gridSize,gridSize);
  bridgeEast = loadImage("mario_terrain/bridge_e.png");
  bridgeEast.resize(gridSize,gridSize);
  goomba0 = loadImage("enemies/enemies/goomba0.png");
  goomba0.resize(25,25);
  goomba1 = loadImage("enemies/enemies/goomba1.png");
  goomba1.resize(25,25);
  marioJump = loadImage("mario_sprites/imageReverser/jump0.png");
  heart = loadImage("heart.png");
}
